### ISSUE TITLE
Pancake Studio Down

### ISSUE THREAD

**Issue by zacbre** [stevengill/pancake-studio#8] opened 2023-05-12 02:02 UTC
Hi guys, has this project been taken down?

I'm not able to access the URL https://pancake.studio anymore.

**Comment by mwbrooks** [comment] 2023-06-15 00:01
Hey @zacbre, sorry about this 😞 

I spent some time today getting access to our hosting, domain, DNS, and so on. The issue seems to be related to the Slack/Salesforce acquisition that caused some accounts to be merged/migrated. I'll keep ya updated! 🙏🏻

**Comment by mwbrooks** [comment] 2023-06-16 16:34
Good morning @zacbre 👋🏻

Good news - https://pancake.studio/ is online! Big thanks to @stevengill who had to work through some internal hosting requests 🙇🏻 The downtime was a result of the company transition and shouldn't happen again.

Sorry about that!

**Closed by mwbrooks** 2023-06-16 16:34 UTC

**Comment by mm-chrisspencer** [comment] 2023-08-01 16:24
https://pancake.studio appears to be down again

**Comment by mwbrooks** [comment] 2023-08-01 17:06
Hi @mm-chrisspencer 👋🏻 

Thanks for letting us know that the domain was down (again) 🙇🏻 We've had some transition pains while moving our accounts and it looks like our DNS record was dropped 🤔 I've now restored it and https://pancake.studio is online 🟢

If this happens again, we'll look into an alternative DNS provider. Sorry for the trouble! 🙏🏻

**Comment by ChrisCarini** [comment] 2025-06-05 19:01
Hi @mwbrooks - it appears that https://pancake.studio/ is down again. 😓

**Comment by mwbrooks** [comment] 2025-06-14 02:13
Hey @ChrisCarini,

Thanks for the heads up! It's been a bonker of a week and I didn't respond to you. I'm sorry about that. However, I saw your message last Thursday and started to dig into it.

This appears to have been an issue on the Heroku backend. We didn't make any DNS changes and I confirmed with our DNS provider that everything was alright. Then I contacted Heroku support who helped to make a fix on their backend. I'm unsure what was causing the issue, but their team resolved it.

I don't love that this has been down again and a DNS issue is quite frustrating. I'm sorry about that. It should be working now, at least.

Once again, thanks for the message. If it wasn't your comment, we would not have noticed it as quickly. 🙇🏻

**Comment by ChrisCarini** [comment] 2025-06-14 02:38
Nice! No worries about not responding right away - life can get hectic, and I understand.

Thanks for getting it back up again! I honestly only noticed because we didn't get a slack alert for an outage. I might set up actual monitoring ("monitor the monitoring stuff") - if I do, I'll hopefully catch it faster next time. 

Thank you, again, both for working to fix the issue, and authoring and hosting this to begin with! 🙏
